name: format-pr

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v1
      - name: Install Formatter
        run: julia --project=test -e 'import Pkg; Pkg.add("JuliaFormatter")'
      - name: Run format
        run: julia --project=docs -e 'using JuliaFormatter; format(".")'

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Format .jl files
          PULL_REQUEST_TITLE: '[AUTO] Format .jl files */Manifest.toml'
          PULL_REQUEST_LABELS: no changelog
          PULL_REQUEST_BRANCH: create-pull-request/format-pr
          BRANCH_SUFFIX: none
      - name: Check output environment variable
        run: echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
